apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-log-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce  # 本地存储仅支持单节点读写
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
